# Pre-commit hooks 配置
# 在 git commit 之前自动运行代码检查和格式化

repos:
  # Python 代码检查和格式化 (Ruff)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      # Ruff linter
      - id: ruff
        name: ruff lint
        args: [--fix]
        types_or: [python, pyi]
      # Ruff formatter
      - id: ruff-format
        name: ruff format
        types_or: [python, pyi]

  # JavaScript/TypeScript 格式化 (Prettier)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: prettier
        types_or: [javascript, jsx, ts, tsx, json, yaml, markdown, css, scss]
        args: [--write]
        additional_dependencies:
          - prettier@3.2.5
          - prettier-plugin-tailwindcss@0.5.11

  # 通用文件检查
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # 检查文件末尾是否有空行
      - id: end-of-file-fixer
      # 检查是否有多余的空白字符
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      # 检查 YAML 文件语法
      - id: check-yaml
        args: [--unsafe]  # 允许自定义标签
      # 检查 JSON 文件语法
      - id: check-json
      # 检查 TOML 文件语法
      - id: check-toml
      # 检查是否有大文件
      - id: check-added-large-files
        args: [--maxkb=1000]
      # 检查是否有合并冲突标记
      - id: check-merge-conflict
      # 检查是否有调试语句
      - id: debug-statements
      # 检查 Python 文件的语法
      - id: check-ast
      # 防止提交到 main/master 分支
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master]

  # 检查密钥泄露
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: detect secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        name: hadolint

# 全局配置
default_language_version:
  python: python3.11
  node: {{ cookiecutter.node_version }}

# CI 配置
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false

