# 监控和可观测性套件
# Prometheus, Grafana, Loki, Jaeger

version: '3.8'

services:
  # Prometheus - 指标收集
  prometheus:
    image: prom/prometheus:latest
    container_name: {{ cookiecutter.project_slug }}-prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - {{ cookiecutter.project_slug }}-monitoring

  # Grafana - 可视化
  grafana:
    image: grafana/grafana:latest
    container_name: {{ cookiecutter.project_slug }}-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin  # 请修改默认密码
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - {{ cookiecutter.project_slug }}-monitoring

  # Loki - 日志聚合
  loki:
    image: grafana/loki:latest
    container_name: {{ cookiecutter.project_slug }}-loki
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./loki:/etc/loki
      - loki_data:/loki
    networks:
      - {{ cookiecutter.project_slug }}-monitoring

  # Promtail - 日志收集器
  promtail:
    image: grafana/promtail:latest
    container_name: {{ cookiecutter.project_slug }}-promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail:/etc/promtail
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    depends_on:
      - loki
    networks:
      - {{ cookiecutter.project_slug }}-monitoring

  # Jaeger - 分布式追踪
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: {{ cookiecutter.project_slug }}-jaeger
    restart: unless-stopped
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "5775:5775/udp"    # accept zipkin.thrift over compact thrift protocol
      - "6831:6831/udp"    # accept jaeger.thrift over compact thrift protocol
      - "6832:6832/udp"    # accept jaeger.thrift over binary thrift protocol
      - "5778:5778"        # serve configs
      - "16686:16686"      # serve frontend
      - "14268:14268"      # accept jaeger.thrift directly from clients
      - "14250:14250"      # accept model.proto
      - "9411:9411"        # Zipkin compatible endpoint
      - "4317:4317"        # OTLP gRPC
      - "4318:4318"        # OTLP HTTP
    networks:
      - {{ cookiecutter.project_slug }}-monitoring

  # Node Exporter - 主机指标
  node-exporter:
    image: prom/node-exporter:latest
    container_name: {{ cookiecutter.project_slug }}-node-exporter
    restart: unless-stopped
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - {{ cookiecutter.project_slug }}-monitoring

  # cAdvisor - 容器指标
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: {{ cookiecutter.project_slug }}-cadvisor
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      - {{ cookiecutter.project_slug }}-monitoring

# 数据卷
volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  loki_data:
    driver: local

# 网络
networks:
  {{ cookiecutter.project_slug }}-monitoring:
    driver: bridge

