# Prometheus 配置文件

global:
  scrape_interval: 15s  # 抓取间隔
  evaluation_interval: 15s  # 规则评估间隔
  external_labels:
    cluster: 'dev'
    project: '{{ cookiecutter.project_slug }}'

# 告警管理器配置（可选）
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#             - 'alertmanager:9093'

# 规则文件
rule_files:
  - '/etc/prometheus/rules/*.yml'

# 抓取配置
scrape_configs:
  # Prometheus 自身
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Node Exporter - 主机指标
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'

  # cAdvisor - 容器指标
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'cadvisor'

  # Backend API
  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']  # 开发环境
        labels:
          service: 'backend'
          env: 'dev'

  # Frontend (如果有指标端点)
  - job_name: 'frontend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          service: 'frontend'
          env: 'dev'

  # PostgreSQL Exporter (如果安装了)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'

  # Redis Exporter (如果安装了)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'

  {% if cookiecutter.enable_ml_api == 'yes' -%}
  # ML API
  - job_name: 'ml-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8001']
        labels:
          service: 'ml-api'
          env: 'dev'
  {% endif -%}

  {% if cookiecutter.enable_audio_api == 'yes' -%}
  # Audio API
  - job_name: 'audio-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8002']
        labels:
          service: 'audio-api'
          env: 'dev'
  {% endif -%}

