# Promtail 配置文件

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker 容器日志
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      # 解析 JSON 格式的 Docker 日志
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
            timestamp: time

      # 解析时间戳
      - timestamp:
          source: timestamp
          format: RFC3339Nano

      # 添加标签
      - labels:
          stream:

      # 输出
      - output:
          source: output

  # 系统日志
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\S+\s+\S+)\s+(?P<hostname>\S+)\s+(?P<service>\S+)(\[(?P<pid>\d+)\])?\:\s+(?P<message>.*)$'

      - labels:
          hostname:
          service:

      - timestamp:
          source: timestamp
          format: Jan _2 15:04:05
          location: Asia/Shanghai

  # 应用日志（JSON 格式）
  - job_name: app-json
    static_configs:
      - targets:
          - localhost
        labels:
          job: app
          __path__: /var/log/{{ cookiecutter.project_slug }}/*.json

    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            logger: logger
            timestamp: timestamp

      - labels:
          level:
          logger:

      - timestamp:
          source: timestamp
          format: RFC3339

  # Kubernetes Pod 日志（如果在 K8s 中）
  # - job_name: kubernetes-pods
  #   kubernetes_sd_configs:
  #     - role: pod
  #   relabel_configs:
  #     - source_labels: [__meta_kubernetes_pod_node_name]
  #       target_label: __host__
  #     - action: labelmap
  #       regex: __meta_kubernetes_pod_label_(.+)
  #     - action: replace
  #       replacement: $1
  #       separator: /
  #       source_labels:
  #         - __meta_kubernetes_namespace
  #         - __meta_kubernetes_pod_name
  #       target_label: job
  #     - action: replace
  #       source_labels:
  #         - __meta_kubernetes_namespace
  #       target_label: namespace
  #     - action: replace
  #       source_labels:
  #         - __meta_kubernetes_pod_name
  #       target_label: pod
  #     - action: replace
  #       source_labels:
  #         - __meta_kubernetes_pod_container_name
  #       target_label: container
  #     - replacement: /var/log/pods/*$1/*.log
  #       separator: /
  #       source_labels:
  #         - __meta_kubernetes_pod_uid
  #         - __meta_kubernetes_pod_container_name
  #       target_label: __path__

