version: 2

# Dependabot 配置 - 自动更新依赖

updates:
  # Python 依赖更新 (pip)
  - package-ecosystem: "pip"
    directory: "/services/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    reviewers:
      - "{{ cookiecutter.github_username }}"
    assignees:
      - "{{ cookiecutter.github_username }}"
    labels:
      - "dependencies"
      - "python"
      - "backend"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      # 忽略主要版本更新（需要手动审查）
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  {% if cookiecutter.enable_ml_api == 'yes' -%}
  # ML API Python 依赖
  - package-ecosystem: "pip"
    directory: "/services/ml-api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 3
    reviewers:
      - "{{ cookiecutter.github_username }}"
    labels:
      - "dependencies"
      - "python"
      - "ml-api"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
  {% endif -%}

  {% if cookiecutter.enable_audio_api == 'yes' -%}
  # Audio API Python 依赖
  - package-ecosystem: "pip"
    directory: "/services/audio-api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 3
    reviewers:
      - "{{ cookiecutter.github_username }}"
    labels:
      - "dependencies"
      - "python"
      - "audio-api"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
  {% endif -%}

  {% if cookiecutter.enable_scraper == 'yes' -%}
  # Scraper Python 依赖
  - package-ecosystem: "pip"
    directory: "/services/scraper"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 3
    reviewers:
      - "{{ cookiecutter.github_username }}"
    labels:
      - "dependencies"
      - "python"
      - "scraper"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
  {% endif -%}

  # npm 依赖更新
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    reviewers:
      - "{{ cookiecutter.github_username }}"
    assignees:
      - "{{ cookiecutter.github_username }}"
    labels:
      - "dependencies"
      - "javascript"
      - "frontend"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    versioning-strategy: increase
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions 更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 3
    reviewers:
      - "{{ cookiecutter.github_username }}"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"

  # Docker 基础镜像更新
  - package-ecosystem: "docker"
    directory: "/services/backend"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 2
    reviewers:
      - "{{ cookiecutter.github_username }}"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/services/frontend"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 2
    reviewers:
      - "{{ cookiecutter.github_username }}"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

