# Frontend Helm Chart 默认配置值

replicaCount: 2

image:
  repository: {{ cookiecutter.docker_registry }}/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}-frontend
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: regcred

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: "{{ cookiecutter.kubernetes_namespace }}-rate-limit@kubernetescrd"
  hosts:
    - host: {{ cookiecutter.domain_name }}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: frontend-tls
      hosts:
        - {{ cookiecutter.domain_name }}

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

env:
  - name: NUXT_PUBLIC_API_BASE
    value: "https://api.{{ cookiecutter.domain_name }}"
  - name: NODE_ENV
    value: "production"

nodeSelector: {}
tolerations: []
affinity: {}

